### ISSUE TITLE
Remove commit msg from calc-stats

### ISSUE THREAD

**Issue by adigulalkari** [adigulalkari/VC-Analyzer#23]
Currently when executed the ```calc-stats``` cmd shows the all commit msgs in the repo. 

<img width="948" alt="image" src="https://github.com/user-attachments/assets/967ac005-c0d5-4a14-a8a3-385d32f8d439">

It isn't really necessary. User can use git log for it.

Change this functionality.

**Comment by Nikhils-179** [comment]
@adigulalkari  /assign
