### ISSUE TITLE
Add CLI Help Documentation for all commands

### ISSUE THREAD

**Issue by adigulalkari** [adigulalkari/VC-Analyzer#7]
Add detailed help documentation for the all command to guide users on how to use it.

Tasks:
- Add descriptions, usage examples, and explanations for the all command and its flags.
- Ensure the command is easy to discover via the CLI help system.

Acceptance Criteria:
- Running ```vc-analyze cmd --help``` should display clear and helpful documentation.
- Provide usage examples for both public and private repositories.

**Comment by seinaryan** [comment]
Sceenshots regarding the changes

![372883034-14013fbd-43b5-4c0c-9971-5d76a144498b](https://github.com/user-attachments/assets/b94e9885-85e3-42e0-9c91-e5b54069b7a9)



![image](https://github.com/user-attachments/assets/524378fc-d21c-4882-97c5-8736acf93420)

**Comment by adigulalkari** [comment]
Need something like this
<img width="714" alt="image" src="https://github.com/user-attachments/assets/169930cf-5852-4762-a67e-44834ae4a3d5">

**Comment by Nikhils-179** [comment]
@adigulalkari  I would like to work on the issue , could you please assign to me

**Comment by adigulalkari** [comment]
sure @Nikhils-179
